# -----------------------------------------------------------------------------
# Main
# -----------------------------------------------------------------------------
log-level: silent
mixed-port: 7890
socks-port: 7891
redir-port: 7892
mode: rule
ipv6: false
allow-lan: true
external-controller: 127.0.0.1:9090
keep-alive-interval: 30
enable-process: true
find-process-mode: always
unified-delay: false
profile:
  store-selected: true
  store-fake-ip: true

sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]

hosts:
  # Сопоставление адресов DoT-серверов
  "dns.adguard-dns.com": ["94.140.14.14", "94.140.15.15"]
  "dns.quad9.net": ["9.9.9.9", "149.112.112.112"]

dns:
  enable: true
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  # enhanced-mode: redir-host
  # listen: 127.0.0.1:6868
  default-nameserver:
    - 94.140.14.14
    - 94.140.15.15
  nameserver:
    - tls://dns.adguard-dns.com
    - https://dns.adguard-dns.com/dns-query
  direct-nameserver:
    - system
  proxy-server-nameserver:
    - tls://dns.quad9.net
    - https://dns.quad9.net/dns-query
  fake-ip-filter:
    - "*.lan"
    - stun.*.*.*
    - stun.*.*
    - time.windows.com
    - time.nist.gov
    - time.apple.com
    - time.asia.apple.com
    - "*.openwrt.pool.ntp.org"
    - pool.ntp.org
    - ntp.ubuntu.com
    - time1.apple.com
    - time2.apple.com
    - time3.apple.com
    - time4.apple.com
    - time5.apple.com
    - time6.apple.com
    - time7.apple.com
    - time1.google.com
    - time2.google.com
    - time3.google.com
    - time4.google.com
    - api.joox.com
    - joox.com
    - "*.xiami.com"
    - "*.msftconnecttest.com"
    - "*.msftncsi.com"
    - "+.xboxlive.com"
    - "*.*.stun.playstation.net"
    - xbox.*.*.microsoft.com
    - "*.ipv6.microsoft.com"
    - speedtest.cros.wr.pvp.net

# -----------------------------------------------------------------------------
# Proxies
# -----------------------------------------------------------------------------
proxies: # LEAVE THIS LINE!

proxy-groups:
  - name: "→ Remnawave"
    type: "select"
    proxies: # LEAVE THIS LINE!

# -----------------------------------------------------------------------------
# Rule providers
# -----------------------------------------------------------------------------
rule-providers:
  geosite-block:
    type: http
    behavior: domain
    format: mrs
    url: https://github.com/aligotr/rule-set-ru/releases/latest/download/geosite_block.mrs
    path: ./rules/geosite_block.mrs
    interval: 86400

  geosite-direct:
    type: http
    behavior: domain
    format: mrs
    url: https://github.com/aligotr/rule-set-ru/releases/latest/download/geosite_direct.mrs
    path: ./rules/geosite_direct.mrs
    interval: 86400

  geoip-proxy:
    type: http
    behavior: ipcidr
    format: mrs
    url: https://github.com/aligotr/rule-set-ru/releases/latest/download/geoip_proxy.mrs
    path: ./rules/geoip_proxy.mrs
    interval: 86400

  geosite-proxy:
    type: http
    behavior: domain
    format: mrs
    url: https://github.com/aligotr/rule-set-ru/releases/latest/download/geosite_proxy.mrs
    path: ./rules/geosite_proxy.mrs
    interval: 86400

  apps-direct:
    type: http
    behavior: classical
    format: yaml
    url: https://github.com/aligotr/rule-set-ru/releases/latest/download/apps_direct.yaml
    path: ./rules/apps_direct.yaml
    interval: 86400

  apps-proxy:
    type: http
    behavior: classical
    format: yaml
    url: https://github.com/aligotr/rule-set-ru/releases/latest/download/apps_proxy.yaml
    path: ./rules/apps_proxy.yaml
    interval: 86400

# -----------------------------------------------------------------------------
# Rules
# -----------------------------------------------------------------------------
rules:
  # --- BLOCK ---
  # 🚫 HTTP3/QUIC
  - AND,((NETWORK,udp),(DST-PORT,443)),REJECT

  # 🚫 Реклама
  - RULE-SET,geosite-block,REJECT

  # --- Локальная сеть ---
  - GEOIP,PRIVATE,DIRECT,no-resolve
  - GEOSITE,PRIVATE,DIRECT

  # --- Процессы ---
  - RULE-SET,apps-direct,DIRECT
  - RULE-SET,apps-proxy,→ Remnawave
  
  # --- DIRECT ---
  # ➡️ DNS - IP
  - IP-CIDR,77.88.8.8/32,DIRECT,no-resolve
  - IP-CIDR,77.88.8.1/32,DIRECT,no-resolve
  - IP-CIDR,77.88.8.88/32,DIRECT,no-resolve
  - IP-CIDR,77.88.8.2/32,DIRECT,no-resolve
  - IP-CIDR,77.88.8.7/32,DIRECT,no-resolve
  - IP-CIDR,77.88.8.3/32,DIRECT,no-resolve

  # ➡️ Domain
  - DOMAIN-KEYWORD,yandex,DIRECT
  - RULE-SET,geosite-direct,DIRECT

  # --- PROXY ---
  # 🔁 DNS - IP
  - IP-CIDR,9.9.9.9/32,→ Remnawave,no-resolve
  - IP-CIDR,149.112.112.112/32,→ Remnawave,no-resolve
  - IP-CIDR,9.9.9.11/32,→ Remnawave,no-resolve
  - IP-CIDR,149.112.112.11/32,→ Remnawave,no-resolve
  - IP-CIDR,9.9.9.10/32,→ Remnawave,no-resolve
  - IP-CIDR,149.112.112.10/32,→ Remnawave,no-resolve

  # 🔁 DNS - Domain
  - DOMAIN-SUFFIX,quad9.net,→ Remnawave

  # 🔁 IP
  - RULE-SET,geoip-proxy,→ Remnawave

  # 🔁 Domain
  - RULE-SET,geosite-proxy,→ Remnawave

  # 🔁 Test
  - OR,((DOMAIN-SUFFIX,myip.com),(DOMAIN-SUFFIX,dnsleaktest.com)),→ Remnawave

  # --- 🏁 FINAL ---
  - MATCH,DIRECT
